### ISSUE TITLE
Fabric Mod 1.20.4 Support

### ISSUE THREAD

**Issue by andywithcatz** [kous500/CurveBuilding#19]
I saw that the mod started to get updates to 1.20.4 again, but it looks like it was for a plugin only. Is the fabric mod for 1.20.4 coming?

**Comment by ajh123** [comment]
There is a 1.20.1 version of the mod. Does it work on 1.20.4? It may do.

**Comment by andywithcatz** [comment]
> There is a 1.20.1 version of the mod. Does it work on 1.20.4? It may do.

Nope. Tested it

**Comment by wacch** [comment]
@andywithcatz 
There are currently no plans to support 1.20.x or later versions, as it is not possible to support them only by fixing dependencies, and also because they do not have enough time to develop them.
If you are a developer, we would appreciate your cooperation by submitting a PR.

**Comment by AFEGaming** [comment]
# I found a solution

The mod actually works on Minecraft 1.20.4 without code changes.

The only thing preventing it from loading is the strict dependency in `fabric.mod.json`:

```json
  "depends": {
    "minecraft": "1.20.1",
    "fabricloader": "\u003e\u003d0.14.0",
    ...
}
```

Changing it to:

```json
  "depends": {
    "minecraft": ">=1.20.1",
    "fabricloader": "\u003e\u003d0.14.0",
    ...
}
```

allows the mod to load and function correctly on 1.20.4.

So at least for 1.20.4, it does seem to work fine.

So widening the version range might be enough.

For convenience, I have attached an edited version of the file below (uploaded as an uncompressed zip file due to file type restrictions):

[curvebuilding-fabric-0.5.0+1.20.1.zip](https://github.com/user-attachments/files/25518791/curvebuilding-fabric-0.5.0%2B1.20.1.zip)

**Comment by AFEGaming** [comment]
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/8f46989a-92e1-4498-9b89-cdcd053d5181" />
